### ISSUE TITLE
As a user, I want to access the DOI UI from outside JPL

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#145]
## 💪 Motivation
...so that can be used by partners in other organizations

## 📖 Additional Details

What remains to be done for the publication outside JPL VPN:

- [x] upgrade deployment of DOI to patched v1.0.1 
- [x] replace authentication with Cognito on ui and service
- [x] create an ASR for the application
- [x] do a security scan

## ⚖️ Acceptance Criteria
**Given** a host client outside the JPL VPN
**When I perform** requests on https://pds.jpl.nasa.gov/tools/doi-editor/
**Then I expect** to be requested an authentication and be able to use the application

**Comment by tloubrieu-jpl** [comment]
This ticket will closed as soon as the DOI Editor is actually open outside JPL network https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1982

A different EPIC will be created to onboard PDS EN operators and Discipline node users.

**Comment by viviant100** [comment]
DOI Editor on gamma is now accessible outside JPL network

**Comment by tloubrieu-jpl** [comment]
doi editor is available on gamma from outside JPL on http://pds-gamma.jpl.nasa.gov/tools/doi-editor
