### ISSUE TITLE
Develop DOI Editor and Service Documentation

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/doi-ui#153]
Various tasks remaining so that the DOI editor can be used:

- [x] set up cognito in production and open outside JPL network @jordanpadams @ramesh-maddegoda 
- [x] set up cronjob for DOI in review to be sent to the PDS EN operators.
- [x] write PDS EN operator guide
- [x] train the PDS EN operators

**Comment by jordanpadams** [comment]
Minimum documentation tasks completed
